[package]
name = "practice"
version = "0.1.0"
authors = ["Abhijith <abhijithg@gmail.com>"]
edition = "2021"

[dependencies]
itertools = "0.9"
rayon = "1.1"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
